using System;
using System.Collections.Generic;
using System.Linq;
using SnapTrace.Generators.Builders;

namespace SnapTree.Generators.Builders;

public class SourceFileBuilder
{
    private readonly List<ClassInterceptorBuilder> _classes = new();

    public SourceFileBuilder WithClass(string name, ClassSituation situation, Action<ClassInterceptorBuilder> config)
    {
        var mb = new ClassInterceptorBuilder(name, situation);
        config(mb);
        _classes.Add(mb);
        return this;
    }

    public string Build()
    {
        return $@"// <auto-generated/>
#nullable enable
namespace System.Runtime.CompilerServices 
{{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    sealed file class InterceptsLocationAttribute(string filePath, int line, int character) : Attribute {{ }}
}}

namespace SnapTrace.Generated
{{
    {string.Join("\n", _classes.Select(c => c.InternalBuild()))}
}}";
    }
}
