using SnapTrace.Generators.Builders;
using SnapTrace.Generators.Definitions;

namespace SnapTrace.Generators.Tests.Builders;

public class SourceFileBuilderTests
{
    private string Normalize(string input) => input.Replace("\r\n", "\n").Trim();

    [Fact]
    public void Build_WithOneClass_GeneratesCorrectFile()
    {
        // Arrange
        var builder = new SourceFileBuilder();
        builder.WithClass("MyNamespace.MyClass", ClassSituation.None, c => {
            c.WithMethod("MyMethod", MethodSituation.None, m => m.AddLocation(@"C:\project\File.cs", 10, 20));
        });

        // Act
        var actual = Normalize(builder.Build());

        // Assert
        var expected = Normalize(@"
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;
using System.Runtime.CompilerServices;
using SnapTrace.Runtime;
using SnapTrace.Runtime.Models;

namespace SnapTrace.Generated
{
    file static class MyClassInterceptor
    {
        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.StaticMethod, Name = ""Record"")]
        private static extern void Record(global::SnapTrace.Runtime.Models.SnapEntry entry);

        // ... method interceptors ...
    }
}
");
        // We'll just check the main structure
        Assert.StartsWith("// <auto-generated/>", actual);
        Assert.Contains("namespace SnapTrace.Generated", actual);
        Assert.Contains("file static class MyClassInterceptor", actual);
    }

    [Fact]
    public void Build_WithMultipleClasses_GeneratesCorrectFile()
    {
        // Arrange
        var builder = new SourceFileBuilder();
        builder.WithClass("MyNamespace.MyClass1", ClassSituation.None, c => {
            c.WithMethod("MyMethod1", MethodSituation.None, m => m.AddLocation(@"C:\project\File1.cs", 10, 20));
        });
        builder.WithClass("MyNamespace.MyClass2", ClassSituation.None, c => {
            c.WithMethod("MyMethod2", MethodSituation.None, m => m.AddLocation(@"C:\project\File2.cs", 30, 40));
        });

        // Act
        var actual = Normalize(builder.Build());

        // Assert
        Assert.Contains("file static class MyClass1Interceptor", actual);
        Assert.Contains("file static class MyClass2Interceptor", actual);
    }
}
