namespace SnapTrace.Generators.Constants;

internal static class AttributeDefinitions
{
    /// <summary>
    /// The attributes served by SnapTrace. All marked with "SNAPTRACE",
    /// meaning that the compilator can chose to ignore them if prompted.
    /// </summary>
    internal const string Definitions = @"
#nullable enable
using System;   
using System.Diagnostics;

// <auto-generated/>
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    internal sealed class InterceptsLocationAttribute : Attribute
    {
        private readonly int _version;
        private readonly string? _data;

        public InterceptsLocationAttribute(int version, string data)
        {
            _version = version;
            _data = data;
        }
    }
}

namespace SnapTrace
{
    [Conditional(""SNAPTRACE"")]
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, Inherited = false)]
    internal sealed class SnapTraceAttribute : Attribute { }

    [Conditional(""SNAPTRACE"")]
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, Inherited = false)]
    internal class SnapTraceContextAttribute : Attribute { }

    [Conditional(""SNAPTRACE"")]
    [AttributeUsage(AttributeTargets.Parameter | AttributeTargets.Property, Inherited = false)]
    internal class SnapTraceIgnoreAttribute : Attribute { }

    [Conditional(""SNAPTRACE"")]
    [AttributeUsage(AttributeTargets.Parameter | AttributeTargets.Property, Inherited = false)]
    internal class SnapTraceDeepAttribute : Attribute { }
}
";
}